### PR TITLE
Show the sessions in a table

### PR DESCRIPTION
**Pull request by jcoyne**
This is only on the admin page.

### CODE REVIEW

**Comment by look** [comment]
😱 

Sacrilege! ;)

**Comment by pcantrell** [comment]
Part of the rationale for the current two-column layout is that older sessions show up at the top of the second column, which prevents the last-added sessions from sucking up all of the attention. I wonder if there's a way to preserve that?

**Comment by jcoyne** [comment]
@pcantrell This is only on the admin page, so finding information is more important than an even distribution.

**Comment by pcantrell** [comment]
Oh, duh! Maybe I should try actually paying attention when reviewing PRs.

**Pull request merged**
