### PR TITLE
Fixes the routes override of the admin configuration checkbox 

### PR DESCRIPTION
**Pull request by caseyhelbling**
This allows us to dynamically toggle the schedule/sessions as the landing
page.

### CODE REVIEW

**Comment by look** [comment]
Haha, that quick hack only lasted 7 years. 😉

**Comment by jcoyne** [comment]
See https://github.com/minnestar/sessionizer/commit/d8e83277cb4e3dc3cf4959d3a297f3ad435aab76

**Comment by jcoyne** [comment]
I see, this is fixing a regression in https://github.com/minnestar/sessionizer/commit/0778997d70fea216f235a5471d0152c6f03d570a

**Comment by caseyhelbling** [comment]
Yah. At some point I introduced a bug by manually overriding the checkbox by updating the routes file to point to `pages#home`. This undoes that hack so the schedules controller can actually do its job.

```class SchedulesController < ApplicationController
  def index
    unless Settings.show_schedule? || params[:force]
      redirect_to home_page_path
     return
    end
```

**Pull request merged**
