### PR TITLE
Update the header maps to point to the recent SVGs

### PR DESCRIPTION
**Pull request by ecaron**
The SVGs should be more mobile friendly with higher contrast.

### CODE REVIEW

**Comment by caseyhelbling** [comment]
Nice I'll get this merged and deployed today. Thanks!

**Comment by caseyhelbling** [comment]
@ecaron This will work better if the maps are in `app/assets/images/maps/*`... Can you make that change? 

Thanks!

**Comment by ecaron** [comment]
Thanks for the suggestion. I got caught off guard with the public assets committed, but I should have known better.

**Comment by caseyhelbling** [comment]
👍

**Pull request merged**
