### PR TITLE
Fix underlying logic with adding presenters.

### LINKED ISSUE #261: Style add presenters search box and Add button
Change this:

image

To be more consistent with this:

image

### LINKED ISSUE #264: Tried to add presenter to Minnebar15
After one of my presenters in Minnebar15 registered with the conference I tried to add him as a presenter but could not find him in the database after half an hour.  The instructions say: "In order to add a presenter to your session, they must be registered in the system." So do they need to be registered with the conference, or registered in Crowdcast, which is the conference software being used?

### LINKED ISSUE #265: Not able to add Presenter who is clearly presenting other sessions
Trying to add Jade Barker who is offering:

https://sessions.minnestar.org/sessions/1234
https://sessions.minnestar.org/sessions/1236

To my session:

https://sessions.minnestar.org/sessions/1232

Keeps saying she has not accepted code of conduct ??

### LINKED ISSUE #304: Problem adding a Presenter who HAS accepted Code of Conduct
Mary Kay Ziniewicz has registered as attendee and has accepted Code of Conduct.  Checkmark appears on her profile page.

But I am unable to add her as a Presenter for our Panel.  Multiple attempts over several days.  Error message says she has not accepted the Code of Conduct.

How can we resolve this?

### PR DESCRIPTION
**Pull request by unsay**
When adding presenters, the JavaScript library does not pass the unique ID, but the person's name to the server. The server then does a lookup using the name, returning the first result.

https://github.com/minnestar/sessionizer/blob/37a8eaa6903c965f80e06b8f73a9f8a2bef15a44/src/app/controllers/presentations_controller.rb#L11-L14

I don't know PostgreSQL's internals well; though I suspect it will return the lowest ID (i.e. oldest account) -- meaning people with duplicate accounts will probably "never accept the CoC".

### Resolution

I don't want to yak-shave the Rails Asset Pipeline, so I'm linking to a CDN with a POJO autocomplete library.

This fixes an issue so at least the person selected does not break the application. Further discussion in #300 to address duplicate names.

refs #300 
closes #304
closes #265
closes #264
refs #120 
closes #261 (winning)

### CODE REVIEW

**Review by experimatt — COMMENTED** [review]
This looks good to me, although I'm concerned about linking directly to the cdn for `autoComplete.js`. I'd feel better if it were saved in the repo somewhere (as a node module?), but that might be a larger strategic discussion.

**Comment by unsay** [comment]
In general, I agree, we don't gain much from a CDN for the libs/resources we have. It does, however, lower management/maintenance surface area for the Rails Asset Pipeline (albeit requiring a network connection for development).

Given [Rails 5.2 was EOL June 2022](https://endoflife.date/rails) and [Ruby 2.7 was EOL March 2023](https://endoflife.date/ruby), I think focusing on those _then_ bringing the JS libs in-line with the current JS/Rails model is where we might want to spend some effort.

**Comment by unsay** [comment]
@experimatt I will change the referenced library to include the SRI hash, which may be enough to securely pin in while we address the larger discussion.

**Comment by unsay** [comment]
@experimatt Good to go.

**Review by experimatt — APPROVED** [review]
Looks good!

**Pull request merged**
